### ISSUE TITLE
Rocketleague bug

### ISSUE THREAD

**Issue by nickeeey** [antonpup/Aurora#185]
Rocketleague change the color to dark blue but the boost and goal stats aren't working.

**Comment by werdna87** [comment]
AFAIK rocket league is not working right now. The updates have messed with the memory locations, so Aurora needs to be updated

**Comment by Sokonomi** [comment]
Is it still dead? I cant get mine to work.

**Comment by santosch** [comment]
Mine neither. I would really love this. :(

**Comment by werdna87** [comment]
if anyone can point me to where the actual memory location are in both rocket league and aurora, i can see what i can do

**Comment by antonpup** [comment]
I pushed a minor update with new Rocket League pointers. It should automatically update when updater is run.

**Comment by santosch** [comment]
Thank you for your work. I installed the update, restartet aurora, but it is still not working for me :( The keyboard just turns blue. 
* I use the current version of RocketLeague and Aurora. 
* Aurora is run as administrator
* my file Pointers/RocketLeague.json matches the one in the dev branch
* I am using window 10 64bit

Any thougts why it still fails for me? :(
Thank you.

**Comment by antonpup** [comment]
It is entirely possible that my submitted pointers were wrong.

What is the version number in the file "version_minor.txt"? Should be 0.5.2

**Comment by Sokonomi** [comment]
My updater doesn't pick up on it for some reason.
It says my 0.5.1d is the latest version?

**Comment by antonpup** [comment]
There should be a file called "ver_minor.txt" it should say "0.5.2"

![](https://puu.sh/sq8UJ/4ce276c161.png)

**Comment by Sokonomi** [comment]
Mine says "0.3.3_1"

**Comment by antonpup** [comment]
Must be a bug in the updater then.. hmm

**Comment by antonpup** [comment]
Run "Aurora-Updater.exe" file. It will check for both minor and major version changes. Which will download the new pointers. I will see if this bug exists on the dev branch.

**Comment by Sokonomi** [comment]
I was firing off the updater from within Aurora (General settings > Updates), that one did not work.
But launching the actual updater file from the root folder did work, it picked up the minor update.
Something to look at maybe. ;)

**Comment by santosch** [comment]
I can confirm the behaviour Sokonomi described. The updater run from the program itself didn't find the minor update, wenn I had closed the program and did run the Aurora-Updater.exe manually the new minor 0.5.2 was installed.

I already did this before reporting that this update did not fix the issue for me (ergo it still exists).
But thank you for your work!

**Comment by antonpup** [comment]
Ok. I will look into this again.

**Comment by santosch** [comment]
Could be interesting: i was just playing and suddenly there where a few flashes of the teamcolor on my keyboard. This happened a few times - but it seemed to be completely random.

**Comment by busaku** [comment]
Hey, in 0.6.0b - the problem isnt fixed or?..
Rocket League still did not working :(

**Comment by ChaosgamesTV** [comment]
What do you think? When will RocketLeague start working again?

**Comment by Poolitzer** [comment]
Can you give an ETA? Please :D

**Comment by simon-wh** [comment]
I'll try and get it updated for each release I do. I'm not sure when I'll
be releasing the next one,but hopefully soon.

**Comment by Poolitzer** [comment]
Sounds good, thanks. Amazing work.

**Comment by Poolitzer** [comment]
Any Update on this? I would love to help. Maybe, dont know, you can show me for once how to do. And I can do this after every RL Update. So you dont have to ;P

**Comment by diogotr7** [comment]
@poolitzer issue #730 could be a good place to start. I've tried for a bit but I can't really seem to find the pointers :(

**Comment by Poolitzer** [comment]
@diogotr7 thanks mate for this link. I gonna search a little bit. The nigth is still young.

**Comment by nben** [comment]
My bad, Aurora requested that I notify the dev of rocket league update but a new issue wasn't really necessary. Latest aurora and rocket league versions seem to not work together (0.6.1-dev4, and rocket league ver from dec 14th).

Is this a case of Aurora needing an update, or is there a feature built into Aurora to find the new pointers?

**Comment by simon-wh** [comment]
@nben I might see if I can get some updated pointers tomorrow (if I remember and have time) as RL doesn't appear to be being updated all the time. I might also try and make a system that downloads latest pointers from the github repo

**Comment by nben** [comment]
Thank you!

**Comment by KillerEnraged** [comment]
Is this going to be updated?

**Comment by Gurjot95** [comment]
Updated as of now.

**Comment by A-Man** [comment]
Would like to point out that this issue is back with the most recent update to RL.

**Comment by StijnOostdam** [comment]
If someone can tell me how to find those addresses then I could update them
