### ISSUE TITLE
Logitech G410 - FN key not working properly

### ISSUE THREAD

**Issue by andrixbooom** [antonpup/Aurora#360]
Everything was fine before I updated to 0.6.0.0.
I have this desktop setup:
Green for WASD, Blue for the arrows, and red for every other key, plus an interactive layer above everything with the arrow flow effect.
The FN key is unaffected, it stays red. I discovered that only this particular key takes the setting from the logitech gaming software.
This also happens when I play other games, I tested this with Dota, LoL, Battleborn and Overwatch.
The FN stays a fixed red.
I chose the G410 setup from the configuration. I also proceeded in reinstalling Aurora, then reapplying the logitech patch. Didn't work.

**Comment by antonpup** [comment]
Fixed. The issue will automatically close when it's released in a new update.

**Comment by andrixbooom** [comment]
thank you very much!

**Comment by yavorovich** [comment]
This issue is still reproduced on my Logitech G410 keyboard. Could it be related to updated firmware?

**Comment by simon-wh** [comment]
@yavorovich Try the [latest development release](https://github.com/antonpup/Aurora/releases). The fix isn't in the stable release yet.
