### ISSUE TITLE
Corsair k95 Platinum  

### ISSUE THREAD

**Issue by ChoosenMEME** [antonpup/Aurora#977]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Corsair K95 Platinum)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other

### Expected behavior: 
Macro Keys 3-6 should light up

### Actual behavior:
Macro Keys 3-6 don´t light up

### How often does this problem occur?
This problem occurs... (allways)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. normal setup trying to add effects to the Macro Keys

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1 dev-3)

**Comment by simon-wh** [comment]
Update to v0.6.1-dev4. The issue has been fixed in that version.

**Comment by Nevoska** [comment]
I can confirm that this issue is happening in v0.6.3, Keys G2-G6 dont light up. And i notice that the led bar on top of the keyboard does not light up too

**Comment by simon-wh** [comment]
@Nevoska That's strange, nothing has changed since the fixes were made for the K95 Plat, so it should be working unless they changed something in the SDK. The SDK has been updated in the dev builds and will be released later today which you should try to see if that fixes the issues for you.

**Comment by Nevoska** [comment]
Still not working on v0.6.4 : (
https://imgur.com/a/GyL4W6S
https://imgur.com/a/oAk5Nvj

**Comment by simon-wh** [comment]
@Nevoska Is this when in a game? If you try a solid fill layer and select those keys does it work?

**Comment by Nevoska** [comment]
Its only in the game. In the desktop all keys and regions works

**Comment by simon-wh** [comment]
@Nevoska  If the game uses the wrapper, you can clone the lights of the keys onto the unlit keys through the Key Cloning on the Wrapper Layer

**Comment by Nevoska** [comment]
Thanks! its way better now. At least its not turned off anymore
